#!/usr/bin/ruby
# I am a comment. Just ignore me.

=begin
This is a block of comment.
This is a comment, too.
This is a comment, too.
I said that already.
=end
puts "This is main Ruby Program"

END {
   puts "Terminating Ruby Program"
}
BEGIN {
   puts "Initializing Ruby Program"
}
